### ISSUE TITLE
Platform problem with firebase

### ISSUE THREAD

**Issue by amatshiye** [putraxor/flutter_desktop_launcher#10]
Every time I try to run my app with the launcher on macos it gives me this exception.

Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method Query#getDocuments on channel plugins.flutter.io/cloud_firestore))

**Comment by putraxor** [comment]
please note that Flutter is UI toolkit, any platform specific plugin won't work on others.
`cloud_firestore` is supposed to be run on mobile, not on desktop
for `io` level you can use [firebase_dart_sdk](https://github.com/putraxor/firebase_dart_sdk) instead
