### ISSUE TITLE
 error while loading shared libraries: libjsoncpp.so.1:

### ISSUE THREAD

**Issue by LinArcX** [putraxor/flutter_desktop_launcher#13]
Hi. i follow yout instructions(on linux), but when i want to run the app:
```
./flutter_launcher 
./flutter_launcher: error while loading shared libraries: libjsoncpp.so.1: cannot open shared object file: No such file or directory

```

**Comment by putraxor** [comment]
Please refer to https://github.com/putraxor/flutter_desktop_launcher/issues/5

**Comment by LinArcX** [comment]
I have arch linux and install equivalent packages.(for example: jsoncpp). but i still have the the issue.
