### ISSUE TITLE
sqflite

### ISSUE THREAD

**Issue by marcobraghim** [putraxor/flutter_desktop_launcher#15]
flutter: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)

I got this exception after ./flutter_launcher

**Comment by putraxor** [comment]
Sqflite is flutter mobile plugin, it won't work on desktop workflow

**Comment by marcobraghim** [comment]
Greate, there's a plan to include it as a feature on desktop?

**Comment by putraxor** [comment]
You can use https://github.com/putraxor/dart-sqlite binding instead, but this binding only supports linux and macos for now
