### ISSUE TITLE
Requesting Flutter Launcher Example For linux

### ISSUE THREAD

**Issue by hamidabdulmalik** [putraxor/flutter_desktop_launcher#16]
You know, this is a wonderfull initiative. But It is clear there is a misunderstanding regarding how the files should be structured in your explanation for linux users. Can you please load a working example for linux that can be downloaded and run without any configuration? Because I have tried everything and it is not just working. Thank you.

**Comment by hamidabdulmalik** [comment]
Or even better, make a step by step video for linux users, and upload the code here on github. Thank you.

**Comment by hamidabdulmalik** [comment]
Ok, I finally got it to work, but apart from the App bar and the floating button, nothing else shows.

**Comment by GroovinChip** [comment]
@hamidabdulmalik please post how you got it to work

**Comment by canewsin** [comment]
https://github.com/canewsin/flutter_desktop_launcher
I had updated the blobs to latest version go to above link to test
