### ISSUE TITLE
Error Launching Flutter App

### ISSUE THREAD

**Issue by omarsawalhah** [putraxor/flutter_desktop_launcher#2]
Hi, 
I followed the steps in the video, but I am getting the following error when running Flutter app
Flutter assets check exist false 
file:///private/var/folders/jh/4hdy6ypx1dnd_bkkgtgcv9r40000gn/T/AppTranslocation/BD644313-4F12-4A1F-BE6A-15F1B3268418/d/build/flutter_assets

**Comment by putraxor** [comment]
don't forget to run `flutter build bundle` inside your project root directory

**Comment by adteven** [comment]
i had  run flutter build bundle still error

file:///private/var/folders/c2/01cfkslx07n7w_83rhdmfyz00000gn/T/AppTranslocation/62E94C5E-62EB-43A6-B6B7-0D6BC5ECF467/d/build/

**Comment by omarsawalhah** [comment]
I have also ran flutter build bundle and I had the same problem.

**Comment by putraxor** [comment]
Are you guys using Mac OS?
Please try this one [Flutter (Firefox Send expired on 24h)](https://send.firefox.com/download/fbf3ec5834/#hSDQEv6bY4V8A_SmT7oJdQ)

**Comment by prasadsunny1** [comment]
the link is expired.please upload it again

**Comment by omarsawalhah** [comment]
Yes I am using Mac OS.

**Comment by putraxor** [comment]
Try this https://github.com/putraxor/flutter_desktop_launcher/releases/download/v0.0.1-mac/Archive.zip

**Comment by omarsawalhah** [comment]
It is working fine now.
Thanks

**Comment by adteven** [comment]
still the error @putraxor  download the archive.zip  osx MacBook Pro (15-inch, 2018  if i run the office demo it works  ，i like the method of yours ,please
