### ISSUE TITLE
Upgrading Flutter broken the Launcher

### ISSUE THREAD

**Issue by iNoles** [putraxor/flutter_desktop_launcher#21]
[ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Can't load Kernel binary: Invalid kernel binary format version.
[ERROR:flutter/shell/common/engine.cc(172)] Could not prepare to run the isolate.
[ERROR:flutter/shell/common/engine.cc(119)] Engine not prepare and launch isolate.
[ERROR:flutter/shell/platform/embedder/embedder_engine.cc(61)] Could not launch the engine with configuration.

**Comment by ghost** [comment]
bump

**Comment by MultiArtsTuts** [comment]
Here is the same error.

> flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel dev, v1.3.9, on Linux, locale pt_BR.UTF-8)
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [✓] Android Studio (version 3.2)
> [✓] VS Code (version 1.31.1)
> [!] Connected device
>     ! No devices available

**Comment by stuartmorgan-g** [comment]
This is a fundamental limitation of distributing binary releases of Flutter runners; see [here](https://github.com/google/flutter-desktop-embedding/tree/master/library#how-to-use-this-code) (which is a readme from the library this runner was built with).

The only solution is to use the same version of Flutter that the owner of this project used to compile it.

**Comment by canewsin** [comment]
https://github.com/canewsin/flutter_desktop_launcher
I had updated the blobs to latest version go to above link to test
