### ISSUE TITLE
Can we build this for windows too?

### ISSUE THREAD

**Issue by prasadsunny1** [putraxor/flutter_desktop_launcher#4]
It's great you were able to compile it for both mac and Linux.
please give me hints on how can I use it/Create on windows.

**Comment by putraxor** [comment]
I can't build for windows since I don't have pc
if you want to build your own please visit https://github.com/google/flutter-desktop-embedding/tree/master/library/windows

**Comment by prasadsunny1** [comment]
I was trying to build this project you mentioned. But fell into weird error (I am a beginner) so halted.
Let me see if I am able to get help.

Thanks

**Comment by putraxor** [comment]
I will publish the windows version on monday

**Comment by prasadsunny1** [comment]
wow, thanks. and also please update the new mac os Flutter.app file so that any new people following the video don't return hopelessly.

**Comment by canewsin** [comment]
https://github.com/canewsin/flutter_desktop_launcher
I had updated the blobs to latest version go to above link to test
