### ISSUE TITLE
Not running on linux

### ISSUE THREAD

**Issue by hamidabdulmalik** [putraxor/flutter_desktop_launcher#6]
whenever I run on linux it gives the error message on debug window as : "Error connecting to the service protocol: Exception: Attempted to connect to Dart observatory 5 times, and all attempts failed. Giving up. The URL was ws://127.0.0.1:49494/ws
Exited (sigterm)"

attached is the screenshot

![error](https://user-images.githubusercontent.com/340532/51040890-aa394300-15c9-11e9-83d5-d37fdafeb121.png)

**Comment by putraxor** [comment]
I think it is a privilege issue, try run your `linux_launcher` with `su`
```
sudo ./linux_launcher
```
Don't forget to provide the logs from the command

**Comment by hamidabdulmalik** [comment]
Just got this message, let me run it and get back to you. Thanks for the prompt response.

**Comment by hamidabdulmalik** [comment]
I just ran it on linux with sudo, but it says :

sudo: ./linux_launcher: command not found

without sudo, there is nothing shown on the command, the only error message is from the debug window.
![error2](https://user-images.githubusercontent.com/340532/51075522-6d3e8080-169d-11e9-8c03-14a743b831f0.png)

**Comment by putraxor** [comment]
please refer to https://github.com/putraxor/flutter_desktop_launcher/issues/9

**Comment by canewsin** [comment]
This is because you copy pasted launch.json without modifying port i think
i clearly mentioned here read and follow below
https://github.com/canewsin/flutter_desktop_launcher
I had updated the blobs to latest version go to above link to test
