### ISSUE TITLE
can't connect to the launcher on linux

### ISSUE THREAD

**Issue by letroll** [putraxor/flutter_desktop_launcher#7]
First thank you for your work!

I'm able to run the launcher but there is an error => https://pastebin.com/wP03rqQx .
And visual code return the following error on launch config=>

Error connecting to the service protocol: FormatException: Unexpected character (at character 310)
...,"avgCollectionPeriodMillis":596460,753000,"used":2540640,"capacity":419...
                                       ^
Exited (sigterm)

**Comment by putraxor** [comment]
The error is complaining about your flutter layout, have you overrided the target platform to fuchsia?

for the second error, try opening http://127.0.0.1:49494/ in your browser, it should open the dart observatory dashboard

**Comment by letroll** [comment]
I have fixed ma layout. The target platform is overrided to fuchsia. The url open the dasboard in a browser

**Comment by putraxor** [comment]
I was using Flutter 1.0 stable channel while compiling the embedder
Sorry I can't help you without further information

**Comment by putraxor** [comment]
Please refer to https://github.com/flutter/flutter/issues/6724
