### ISSUE TITLE
Error retrieving accessibility bus address:

### ISSUE THREAD

**Issue by Ess-Soft** [putraxor/flutter_desktop_launcher#8]
> ayoub@DeepinOS:~/Android/Apps/flutterProjects/myApp/linux_launcher$ ./flutter_launcher
> (flutter_launcher:12026): dbind-WARNING **: 14:39:30.293: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Null pointer on window

my project file tree looks like this:
-MyApp
  |--adnroid
  |--ios
  |--lib
  |--linux_launcher
      |----build
      |----lib
      |----flutter_launcher <== executable

when i execute `./flutter_launcher` it throws that error ! even with `sudo ./flutter_launcher`

**Comment by putraxor** [comment]
duplicate https://github.com/putraxor/flutter_desktop_launcher/issues/9
