### ISSUE TITLE
Having problems on Ubuntu 18.04

### ISSUE THREAD

**Issue by GroovinChip** [putraxor/flutter_desktop_launcher#9]
The steps I've taken:

1. Downloaded the repo per the readme
2. Extracted the repo zip
3. Extracted the linux zip and placed in my project
4. Added the specified code to main.dart
5. Ran `flutter build bundle`
6. Updated `launch.json` as specified

This process did not generate an executable for me to click in my project directory so they app could open. I'm not sure exactly how to run the app at this point, or what I need to do to get this working.

**Comment by GroovinChip** [comment]
@putraxor are you able to help out with this please?

**Comment by putraxor** [comment]
Make sure you have the `linux_launcher` inside your project, that is the executable launcher

**Comment by GroovinChip** [comment]
![image](https://user-images.githubusercontent.com/4250470/51289599-d17b8000-19ce-11e9-92a7-beece1774cc5.png)

Like this? Because this is my current configuration.

**Comment by putraxor** [comment]
my bad, I mean `flutter_launcher`. it is supposed to be inside your root project as well as `build/` and `lib/` from `linux_launcher/` dir

**Comment by GroovinChip** [comment]
So my current file structure as you see in the screenshot is fine? How do I execute `flutter_launcher`? What is the command?

**Comment by putraxor** [comment]
No, just copy all contents inside `linux_launcher` into your root project then run `flutter_launcher` as normal executable file, if it doesn't work you may need to `chmod a+x ./flutter_launcher` if it is can't be open by double click, just open it via terminal

**Comment by GroovinChip** [comment]
`No, just copy all contents inside linux_launcher into your root project`

This poses a problem as flutter projects have a `build` folder already. Will renaming the `build` folder from `linux_launcher` cause any issues?

**Comment by putraxor** [comment]
there is nothing to be overwritten, so it will never cause any issue, just make sure to delete all those files when you run it on mobile or your apk/ipa size will grow bigger
